### ISSUE TITLE
updating to Open Core 0.8.X? 

### ISSUE THREAD

**Issue by Crisedu** [ARGAMX/Hackintosh-Intel-i9-10850k-MSI-Z490-GAMING-EDGE-WIFI#4]
hi, how u doing mate? are u thinking to update this efi to the new opencore version? i have the same hardware as you and im thinking to use them butt could be there any problem now?

**Comment by ARGAMX** [comment]
@Crisedu hi man. thank you for you comment.
yes, of course I am thinking about it periodically.
currently I am on Monterey 12.3 and OpenCore 0.8.0 and it working smooth.
also I don't see any improvements in OpenCore ChangeLog related to macOS 12 since OpenCore 0.7.9.
only macOS 13 improvements, which currently still in beta.
so I believe even OpenCore 0.8.0 should work good with macOS 12.5.
I will update OpenCore in this repo bit later.

**Comment by ARGAMX** [comment]
@Crisedu repo updated to 'Open Core 0.8.4'.
Enjoy 😉
